### ISSUE TITLE
ImportError: No module named util_hmctp

### ISSUE THREAD

**Issue by NouhaThabet** [aolimelo/kged#1]
Hello, i am having issue in following commands when using dataset nobelprize-errdet-ek1-p0.010000.npz and the other data sets as well.
`python rank_facts.py nobelprize-errdet-ek1-p0.010000.npz -m patybred -o ranked_dataset.pkl -sp learned-model.pkl `
`python generate_errors.py nobelprize-errdet-ek1-p0.010000.npz -pe 0.01 -ek 1`
`python detect_errors.py nobelprize-errdet-ek1-p0.010000.npz -m patybred -o ranked_dataset.pkl -sp learned-model.pkl `

error states that
`Traceback (most recent call last):
  File "generate_errors.py", line 128, in <module>
    type_hier = load_type_hierarchy(args.input)
  File "/home/nouha/Documents/new_kged/kged/util.py", line 176, in load_type_hierarchy
    hierarchy = dataset["type_hierarchy"].item() if "type_hierarchy" in dataset else None
  File "/home/nouha/Documents/new_kged/env/lib/python2.7/_abcoll.py", line 388, in __contains__
    self[key]
  File "/home/nouha/Documents/new_kged/env/lib/python2.7/site-packages/numpy/lib/npyio.py", line 251, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/nouha/Documents/new_kged/env/lib/python2.7/site-packages/numpy/lib/format.py", line 657, in read_array
    array = pickle.load(fp, **pickle_kwargs)
ImportError: No module named util_hmctp
`
how to fix that issue, waiting for your reply.
Thank you.

**Comment by aolimelo** [comment]
I made an update to the code, and I think it should work now.
Btw, you don't need to run generate_errors.py on nobelprize-errdet-ek1-p0.010000.npz because this dataset already contains synthesized errors.
Let me know if the works now.

**Comment by NouhaThabet** [comment]
Thank you for the quick reply. I have new issues, I resolve some of them and I'm still resolving the others. I will post a new issue if it doesn't work :)
By the way I think that there is one missing file the BblBRED. Because I got this error. 
`ImportError: No module named bblbred`

**Comment by HongAHongzhiyu** [comment]
> Thank you for the quick reply. I have new issues, I resolve some of them and I'm still resolving the others. I will post a new issue if it doesn't work :)
> By the way I think that there is one missing file the BblBRED. Because I got this error.
> ImportError: No module named bblbred

Hello, I hava learned this paper nowadays. However, there is something confused happened. Would it possible for me to communicate with you by e-mail? If possible, i'll be very grareful to you.
Thanks a lot.
